version: "3.9"
services:
  test:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: "test"
    ports:
      - "8010:8010"
    networks:
      - nets
networks:
  nets: